# Ant
# Build your Java projects and run tests with Apache Ant.
# Add steps that save build artifacts and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master
- azure-pipelines

pr:
- master

strategy:
  matrix:
    linux:
      imageName: "ubuntu-18.04"
      CONAN_GCC_VERSIONS: 7
      CONAN_CLANG_VERSIONS: 6.0
    macHighSierra:
      imageName: "macos-10.13"
      CONAN_APPLE_CLANG_VERSIONS: 10.0
    macMojave:
      imageName: "macos-10.14"
      CONAN_APPLE_CLANG_VERSIONS: 11.0
    windows:
      imageName: "vs2017-win2016"
      CONAN_VISUAL_VERSIONS: 15
  maxParallel: 4

pool:
  vmImage: $(imageName)

variables:
  CONAN_USERNAME: "simcenter"
  CONAN_LOGIN_USERNAME: "elhaddad"
  CONAN_CHANNEL: "testing"
  CONAN_UPLOAD: "https://api.bintray.com/conan/nheri-simcenter/simcenter"
  CONAN_NON_INTERACTIVE: 1

steps:
# Maven
# Build, test, and deploy with Apache Maven
- task: Maven@3
  inputs:
    mavenPomFile: 'EQHazard/pom.xml' 
    goals: 'package'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: 'default'
    jdkArchitectureOption: 'x64'
    
    
# CMake
# Build with the CMake cross-platform build system
- task: CMake@1
  displayName: CMake Configuration
  inputs:
    workingDirectory: 'build'
    cmakeArgs: '..'
    
# CMake
# Build with the CMake cross-platform build system
- task: CMake@1
  displayName: CMake Build
  inputs:
    workingDirectory: 'build'
    cmakeArgs: '--build .'

- script: |
    pip install wheel
    pip install conan --upgrade
    pip install conan_package_tools bincrafters_package_tools
  displayName: Conan Installation
  failOnStderr: false

- script: |
    conan -v
    conan remote list
    conan user
    conan remote list
    python build.py
  displayName: Conan Packaging
  failOnStderr: false
